" Use space instead of tabs 4 chars
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set shiftround

" Some files get two spaces
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType javascript setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType puppet setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType htmldjango setlocal ts=2 sts=2 sw=2 expandtab
autocmd BufRead,BufNewFile *.tf setlocal ts=2 sts=2 sw=2 expandtab

" text wrapping
set nowrap  " dont auto wrap on load
set fo-=t   " dont wrap when typing

" Enable auto indenting
filetype plugin indent on

" Identing options.
set autoindent

" Dark background
set background=dark

" Syntax highlighting of course.
syntax enable

" Enable 256 colours
set t_Co=256

" Colorscheme
colorscheme jellybeans

" Add column at 80 char
set colorcolumn=80
highlight ColorColumn ctermbg=232

" line numbers on
set number

" mouse mode
set mouse=a

" Highlight matching parenthesis
set showmatch

" show autocompletion menu when opening files
set wildmenu

" fix backspace
set bs=2

" easier indenting of code blocks
vnoremap < <gv
vnoremap > >gv

" Automatically resize splits
autocmd VimResized * wincmd =

" Global replace by default
set gdefault

" If i search in uppercase, it's case sensitive. If I search in lowercase,
" it isn't.
set smartcase
" Search as I type
set incsearch

" Scroll sideways a character at a time, rather than a screen at a time
set sidescroll=1

" Allow tab completion in command bar
set wildmenu
set wildmode=full

" make status bar 2 lines
set laststatus=1

" show hidden characters
nnoremap <silent><F6> :set list!<CR>

" Set to auto read when a file is changed from the outside
set autoread

" Stops the cursor reaching the bottom of the screen
set scrolloff=3

" tap F3 to toggle line numbers
nnoremap <silent><F3> :set number!<CR>

" show spelling mistakes by pressing F10. Move over a word and press tap z=
" (not in insert mode) to get a list of suggestions
noremap <silent><F10> :set spell!<CR>

" backup options
set backup " enable backups
set backupdir=~/tmp,/tmp " backups (~)
set directory=~/tmp,/tmp " swap files

" Map leader W to save without sudo
noremap <Leader>w :w !sudo tee % > /dev/null

" Format JSON files to be readable
nnoremap <Leader>f :%!python -m json.tool<CR>

" Create undo dir to save undo after closing files
set undofile
set undodir=~/.vim/undodir
