#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# User configuration

# Source aliases
if [ -f $HOME/.shell_aliases ]; then
    source $HOME/.shell_aliases
fi

if [ -f ~/.profile ] ; then
    source $HOME/.profile
fi

# Source nvm
export NVM_DIR="/home/mitch/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Source mkvirtualenv script add ~/.virtualenv directory containing virtualenv's
if [ -f $HOME/.local/bin/virtualenvwrapper.sh ] ; then
    export WORKON_HOME=$HOME/.virtualenvs
    export PROJECT_HOME=$HOME/prog/python
    source $HOME/.local/bin/virtualenvwrapper.sh
fi

# Enable ctl-r history search
bindkey -v
bindkey '^R' history-incremental-search-backward
