#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# User configuration

# Source aliases
if [ -f $HOME/.shell_aliases ]; then
    source $HOME/.shell_aliases
fi

if [ -f ~/.profile ] ; then
    source $HOME/.profile
fi

# Enable ctl-r history search
bindkey -v
bindkey '^R' history-incremental-search-backward

# Set correct TERM if running tmux
[[ $TMUX != "" ]] && export TERM="screen-256color"
